### ISSUE TITLE
I get errors after the initial run

### ISSUE THREAD

**Issue by jviola60** [edit4ever/script.module.zap2xml#23]
After I get the initial download my guide never gets updated again.  When I tail the zap2xml.log file I see this:
 File "/storage/.kodi/addons/script.module.zap2xml/zap2xml.py", line 818, in handle_data
    handleTags(data)
  File "/storage/.kodi/addons/script.module.zap2xml/zap2xml.py", line 387, in handleTags
    setOriginalAirDate()
  File "/storage/.kodi/addons/script.module.zap2xml/zap2xml.py", line 271, in setOriginalAirDate
    if cp[10:13] != '0000':
TypeError: 'int' object has no attribute '__getitem__'

If I go into Kodi and remove and reinstall it then I can get another 14 days of guide information.   I'm running your latest version that I found on libreelec forum.

**Comment by edit4ever** [comment]
Strange - first time I've heard of this error.
If you're comfortable editing zap2xml.py - open it up and replace lines 206-265 with the text from the following file:

[oad update.txt](https://github.com/edit4ever/script.module.zap2xml/files/864956/oad.update.txt)

** sorry I tried posting the code but the github system removes the extra spaces.  Generally this is why I work issues in the LE forum.

If that generates an error for you - please post it.  Thanks!

**Comment by jviola60** [comment]
Sorry for the delay.  I've been on holidays and traveling for work.   I just looked at the code you sent me.  You wanted me to replace line 206-265?   What I currently have that looks close to the code you sent is on lines 269-274:  Here it is.  Is this what you want me to replace or were you correct with lines 206-265?

def setOriginalAirDate():
    global cp,cs,sch
    if cp[10:13] != '0000':
        if "originalAirDate" not in programs[cp] or \
        int(schedule[cs][sch]["time"]) < int(programs[cp]["originalAirDate"]):
            programs[cp]["originalAirDate"] = schedule[cs][sch]["time"]

Regards,
Jeff

**Comment by jviola60** [comment]
Replacing the code you sent me with what I listed above I get the following errors in the zap2xml.log file.
2017-04-18 16:28:47,641 ('Linux', 'LibreELEC', '4.4.13', '#1 SMP Sat Nov
2017-04-18 16:28:47,642 Found openelec node name or /storage/.kodi/addons
2017-04-18 16:28:47,721 Reading config file: /storage/.kodi/addons/script

2017-04-18 16:28:47,847 Exception
2017-04-18 16:28:47,851 Traceback (most recent call last):
  File "/storage/.kodi/addons/script.module.zap2xml/zap2xml.py", line 205
    parseGrid(fn) #data read in and unicode it
  File "/storage/.kodi/addons/script.module.zap2xml/zap2xml.py", line 110
    p.feed(b)
  File "/home/chewitt/LibreELEC.70-official/build.LibreELEC-RPi2.arm-7.0.
  File "/home/chewitt/LibreELEC.70-official/build.LibreELEC-RPi2.arm-7.0.
  File "/storage/.kodi/addons/script.module.zap2xml/zap2xml.py", line 820
    handleTags(data)
  File "/storage/.kodi/addons/script.module.zap2xml/zap2xml.py", line 398
    setOriginalAirDate()
  File "/storage/.kodi/addons/script.module.zap2xml/zap2xml.py", line 272
    date = programs[cp]["originalAirDate"]
KeyError: 'originalAirDate'

**Comment by edit4ever** [comment]
You are correct - I had the line numebrs wrong for some reason.

I may have an issue with consitency with the capital O.

Try replacing with this: 
[oad v2.txt](https://github.com/edit4ever/script.module.zap2xml/files/935222/oad.v2.txt)

**Comment by jviola60** [comment]
I'm still getting errors.   Here my zap2xml.py and zap2xml.log file.   
[zap2xml.zip](https://github.com/edit4ever/script.module.zap2xml/files/949427/zap2xml.zip)

**Comment by edit4ever** [comment]
One of the issues in the log shows that you do not have the 6 hour grid selected on the zap2it preferences (screener website) - log in to the website and change your preferences.

You should select the options for 6 hour grid and show only my favorite channels.  Once you do that - try rerunning the grabber and post the log if there is an error.

P.S.  If you haven't setup favorites on the screener website, please take the time to select only the channels you want downloaded as favorites.   This will speed up the download by decreasing the amount of data pulled in.
